# .github/workflows/deploy.yml
name: Despliegue a GitHub Pages

on:
  push:
    branches:
      - main # O la rama donde está tu código fuente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # O la versión de Node que necesites

    - name: Instalar dependencias
      run: npm ci # O yarn ci

    - name: Construir la aplicación
      run: npm run build

    - name: Desplegar en GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # Rama donde se desplegará la aplicación
        folder: dist # Carpeta donde se encuentra la build de Vue
